### ISSUE TITLE
Code blocks do scroll

### ISSUE THREAD

**Issue by johnhenriksson** [thegeeklab/hugo-geekblog#506]
I'm using theme version v0.2.6.1 and it does not work with horizontal scroll in code blocks

My blog is at https://nerd-geek.com/blog/2020/build-ubuntu-vm-with-packer-on-vsphere/

<img width="1197" alt="image" src="https://github.com/thegeeklab/hugo-geekblog/assets/10085800/17446747-3c48-4470-a120-f6f39860e646">

I'm using these settings in my hugo.toml file

```toml
# Geekblog required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
```
